// Prompt is "Generate a 200-word story with a difficulty level of 1 (out of 5) about [ARRAY VALUE]"

const storyPrompts = [
  "outer space",
  "the deep sea",
  "the solar system",
  "time travel",
  "spaceships",
  "the stars in the sky",
  "exploring new planets",
  "a supernova",
  "space flight",
  "a walk on Mars",
  "the rings of Saturn",
  "the distance between stars",
  "light years",
  "riding a bike to the moon",
  "the planet jupiter",
  "the deep ocean",
  "whales",
  "jumping dolphins",
  "where ocean waves come from",
  "a silly axolotl",
  "the deepest part of the ocean",
  "surfing",
  "surfing the biggest wave",
  "sailing across the ocean",
  "a whale named Bob",
  "a jungle adventure",
  "rainforests",
  "a monkey named Hoo",
  "a mysterious flower",
  "why leaves are green",
  "climbing a redwood tree",
  "a magical treehouse",
  "the tallest mountain",
  "a sabertooth tiger",
  "a grizzly bear named Ella",
  "how dogs came from wolves",
  "a sneaky cat",
  "how fast a cheetah can run",
  "my new dog, Charlie",
  "why dogs bark",
  "why cats have whiskers",
  "bears hibernating for winter",
  "why dogs sleep so much",
  "a puppy named Roar",
  "a magic bike",
  "a boy wizard",
  "an adventurous wizard named Jenna",
  "a goblin with a heart of gold",
  "where halloween came from",
  "why leaves change colors in the fall",
  "a magical halloween costume",
  "a singer called Pumpkin Spice",
  "why the seasons change",
  "the best summer ever",
  "a surprise summer vacation",
  "how plants know it's spring",
  "where the sun goes at night",
  "a snowy adventure",
  "a grumpy yet funny snowman",
  "the north pole",
  "why the sky is blue",
  "why lightning happens during storms",
  "a championship soccer match",
  "an underdog football team",
  "traveling to another country",
  "a gymnastics superstar",
  "why it rains",
  "how seeds become plants",
  "why we dream",
  "how money doesn't grow on trees",
  "the best birthday cake",
  "how chocolate is made",
  "an ice cream party",
  "the chocolate cake food fight",
  "the tallest trees in the world",
  "why penguins huddle together",
  "why we come back down when we jump",
  "why barns are red",
  "how long it would take to drive to the moon",
  "abraham lincoln",
  "flying an airplane through the night sky",
  "a super short yet awesome basketball player",
  "the olympics",
  "magic at the movies",
  "monster trucks",
  "why flowers are colorful",
  "a trip to pluto",
  "the great wall of china",
  "the grand canyon",
  "the lost treasure",
  "my pet giraffe",
  "why you float in outer space",
];

// Themes:
// space, nature (ocean, jungle, forest, mountains), magic (wizards, fairies),
// friends (best friends), exploration, sports (basketball, football, baseball, gymnastics, soccer),
// perservearance, seasons, getting around (bikes, scooters), water (surfing), science questions

export default storyPrompts;
